### PR TITLE
Asynchronous video engine

### PR DESCRIPTION
**Pull request by tlecomte**
Dear Martin,

I am making a second PR to go a bit further than what PR#318 did. In addition to decoding frames asynchronously in a decoder that lives in a separate thread, this PR also makes the video opening asynchronous. This avoids duplication of work between the engine and the decoder classes, which were both opening the video in PR#318. Now the decoder sends a signal with the video information when it has finished opening it.

Thanks,

Timothée

### CODE REVIEW

**Comment by tlecomte** [comment]
Hi Martin! The last commit fixed a test issue. Now that Travis-CI also fixed their problems regarding stalled builds on MacOS, it seems that all the lights are now green :)

**Comment by tlecomte** [comment]
@MartinDelille Dear Martin, this PR went a little bit further again :)
Without changing the code too much really (going async was the hardest part), Joker is now able to work nicely on non-MJPEG, i.e. MP4 and such !

Playing forward and seeking work really fine.

The one remaining situation that is not well optimized is going back in time. This is because non-MJPEG streams are really designed to be decoded forward in time, with the mechanism of keyframes. This situation occurs probably quite frequently when Joker is synchronised with an external audio workstation, and has to adjust its clock back in time. This is something that may need to be tested a bit, and improved if necessary. It may not be that bad at all.

I hope you will like that ! I am sure users will love to be able to work on MP4 instead of having to convert to MJPEG everytime!

**Comment by tlecomte** [comment]
Dear Martin,

One more significant improvement: the code in this PR now does Read-ahead decoding! :)

The logic is the following:
1) the engine (PhVideoEngine) passes frame requests to the decoder (PhVideoDecoder),
2) the engine always makes sure that 5 frames are requested in advance,
3) the engine stores these 5 frames from the future, and also keeps 2 frames from the history

So when the clock ticks and the next frame needs to be drawn, it is already available!
When Joker is synced to an external clock source via LTC or MTC, if it needs to go forward up to 5 frames or backwards up to 2 frames to stay in sync with the clock, the frames are already there!

All of this works both for MJPEG and MP4. Seeking is good. Playing in reverse is still not completely perfect with MP4 (no graphical glitches, just not smooth), but it is ok. I have some ideas to improve that part, but I'm not sure this is worth it.

**Comment by tlecomte** [comment]
And now tests pass :)
(AppVeyor fails to build, but it's not related to this PR: it cannot download ffmpeg)

**Comment by MartinDelille** [comment]
replace by #345

**Pull request closed without merging**
