### PR TITLE
Add preference combobox to setup the LTC timecode

### PR DESCRIPTION
**Pull request by tlecomte**
Dear Martin, this PR adds a combobox in the settings to force a specific LTC timecode. This has proved very useful to ensure proper sync between the audio workstation and the video.

Thanks for considering this PR!

### CODE REVIEW

**Comment by tlecomte** [comment]
Dear @MartinDelille the 2 errors in Travis for this PR are fixed in #423.

**Comment by tlecomte** [comment]
Dear @MartinDelille do you think this one could be merged ? The 2 errors on Travis are due to their update of Ubuntu, it looks like it can't install Qt correctly with that new version, but the unit tests (on Mac) are all ok.

**Comment by tlecomte** [comment]
Dear @MartinDelille no more errors in this PR 😄 Do you think it could be merged ?

**Comment by tlecomte** [comment]
This would fix #249

**Comment by MartinDelille** [comment]
Thanks again for your valuable contribution @tlecomte !

**Comment by tlecomte** [comment]
Thanks @MartinDelille !

**Pull request merged**
